version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 796245059390.dkr.ecr.us-west-2.amazonaws.com
      - BASE_REPO_URI=796245059390.dkr.ecr.us-west-2.amazonaws.com/pytorch-base
      - KOHYA_REPO_URI=796245059390.dkr.ecr.us-west-2.amazonaws.com/kohya-training
      - IMAGE_TAG=ultra-lean
      - echo Build started on `date`
      
  build:
    commands:
      # Stage 1: Pull existing pytorch-base:ultra-lean (skip rebuild to avoid Docker Hub rate limits)
      - echo "=== Pulling existing pytorch-base:ultra-lean ==="
      - docker pull $BASE_REPO_URI:$IMAGE_TAG
      - docker tag $BASE_REPO_URI:$IMAGE_TAG pytorch-base:$IMAGE_TAG
      
      # Stage 2: Build kohya-training:ultra-lean
      - echo "=== Building kohya-training:ultra-lean ==="
      - docker build -t $KOHYA_REPO_URI:$IMAGE_TAG .
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing kohya-training image...
      - docker push $KOHYA_REPO_URI:$IMAGE_TAG
      - echo "Both images pushed successfully:"
      - echo "  pytorch-base:ultra-lean"
      - echo "  kohya-training:ultra-lean"

# Use a larger instance for faster builds
environment:
  compute-type: BUILD_GENERAL1_LARGE
  image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
  type: LINUX_CONTAINER
  privileged-mode: true